= Lenovo Chromebook Duet 5 (13”)
include::_support/common.inc[]

== Device-specific notes

It works 

=== Building image

---
nix-build --argstr device lenovo-homestar -A outputs.default
cp /nix/store/(hash)/mobile-nixos-lenovo-homestar.img  /dev/sdX
sync
mount /dev/sdX /mnt
vim /mnt/etc/shadow # set root password
cp /nix/store/(hash)/mobile-nixos-lenovo-homestar.img  /mnt
---

=== Developer mode

For more details the link:https://chromium.googlesource.com/chromiumos/docs/+/HEAD/debug_buttons.md#Firmware-Menu-Interface[
Firmware Menu Interface] section from the upstream documentation can be read.

You will need to:

. Boot in _Recovery mode_ by powering on using `Power` + `Volume-Up` + `Volume-Down`
. Activate Developer mode by navigating the on-screen menu
. Boot into chromeos and get the command prompt through VT-2
. Enable USB booting

Note that this is only to allow you to boot unverified images.

You may want to configure other options with GBB flags. This is left as an
exercise to the reader.

=== Installating

Boot from usb and do the following operations

---
sudo cp /mobile-nixos-lenovo-homestar.img /dev/mmcblk1
# Or, sudo cp /dev/sda /dev/mmcblk1
sync
sudo fdisk /dev/mmcblk1
# e 2 : extend second partition
---

reboot and nixos-generate-config

=== Wi-Fi support

The Wi-Fi interface requires the modem to be initialized, even on non-LTE
devices.

The modem requires currently unredistributable firmware. It has been overlaid
in the package set as `chromeos-sc7180-unredistributable-firmware`.

For the time being, you will need to manually add this to your configuration
for Wi-Fi.

[source,nix]
----
{ /* configuration.nix */
  hardware.firmware = [
    pkgs.chromeos-sc7180-unredistributable-firmware
  ];
}
----

You will also need to connect with an alternative connection with the
installer, or build it with the firmware yourself.
